//utils
export const START_LOADING = 'START_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//auth
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const LOGOUT = 'LOGOUT';

//tables
export const TABLES_LOADED = 'TABLES_LOADED';
export const TABLE_DELETED = 'TABLE_DELETED';
export const TABLE_ADDED = 'TABLE_ADDED';

//menu items
export const MENU_ITEMS_LOADED = 'MENU_ITEMS_LOADED';
export const DELETE_MENU_ITEM = 'DELETE_MENU_ITEM';
export const ADDED_MENU_ITEM = 'ADDED_MENU_ITEM';
export const MENU_ITEM_CATEGORIES_LOADED = 'MENU_ITEM_CATEGORIES_LOADED';
export const EDIT_MENU_ITEM = 'EDIT_MENU_ITEM';
export const ADDED_MENU_ITEM_CATEGORY = 'ADDED_MENU_ITEM_CATEGORY';
export const DELETE_MENU_ITEM_CATEGORY = 'DELETE_MENU_ITEM_CATEGORY';
export const CHANGE_MENU_ITEM_CATEGORIES_ORDER =
  'CHANGE_MENU_ITEM_CATEGORIES_ORDER';
export const CLOSE_OR_OPEN_MENU_ITEM = 'CLOSE_OR_OPEN_MENU_ITEM';
export const START_LOADING_MENU_ITEMS = 'START_LOADING_MENU_ITEMS';
export const FINISH_LOADING_MENU_ITEMS = 'FINISH_LOADING_MENU_ITEMS';
export const START_LOADING_CATEGORIES = 'START_LOADING_CATEGORIES';

//reservation
export const OPEN_NEW_RESERVATION = 'OPEN_NEW_RESERVATION';
export const LOADED_TABLE_RESERVATIONS = 'LOADED_TABLE_RESERVATIONS';
export const START_LOADING_TABLE_RESERVATIONS =
  'START_LOADING_TABLE_RESERVATIONS';
