//utils
export const START_LOADING = 'START_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//auth
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const LOGOUT = 'LOGOUT';

//tables
export const TABLES_LOADED = 'TABLES_LOADED';
export const FAILED_TO_LOAD_TABLES = 'FAILED_TO_LOAD_TABLES';
export const TABLE_DELETED = 'TABLE_DELETED';
export const FAILED_TO_DELETE_TABLE = 'FAILED_TO_DELETE_TABLE';
export const TABLE_ADDED = 'TABLE_ADDED';
export const FAILED_TO_ADD_TABLE = 'FAILED_TO_ADD_TABLE';

//menu items
export const MENU_ITEMS_LOADED = 'MENU_ITEMS_LOADED';
export const FAILED_TO_LOAD_MENU_ITEMS = 'FAILED_TO_LOAD_MENU_ITEMS';
export const DELETE_MENU_ITEM = 'DELETE_MENU_ITEM';
export const FAILED_TO_DELETE_MENU_ITEM = 'FAILED_TO_DELETE_MENU_ITEM';
export const ADDED_MENU_ITEM = 'ADDED_MENU_ITEM';
export const FAILED_TO_ADD_MENU_ITEM = 'FAILED_TO_ADD_MENU_ITEM';
export const MENU_ITEM_CATEGORIES_LOADED = 'MENU_ITEM_CATEGORIES_LOADED';
export const FAILED_TO_LOAD_MENU_ITEM_CATEGORIES =
  'FAILED_TO_LOAD_MENU_ITEM_CATEGORIES';
export const ADD_WANTED_EDIT_MENU_ITEM_IN_STATE =
  'ADD_WANTED_EDIT_MENU_ITEM_IN_STATE';
export const EDIT_MENU_ITEM = 'EDIT_MENU_ITEM';
export const FAILED_TO_EDIT_MENU_ITEM = 'FAILED_TO_EDIT_MENU_ITEM';
export const ADDED_MENU_ITEM_CATEGORY = 'ADDED_MENU_ITEM_CATEGORY';
export const FAILED_TO_ADD_MENU_ITEM_CATEGORY =
  'FAILED_TO_ADD_MENU_ITEM_CATEGORY';
export const DELETE_MENU_ITEM_CATEGORY = 'DELETE_MENU_ITEM_CATEGORY';
export const FAILED_TO_DELETE_MENU_ITEM_CATEGORY =
  'FAILED_TO_DELETE_MENU_ITEM_CATEGORY';
export const CHANGE_MENU_ITEM_CATEGORIES_ORDER =
  'CHANGE_MENU_ITEM_CATEGORIES_ORDER';
export const FAILED_TO_CHANGE_MENU_ITEM_CATEGORIES_ORDER =
  'FAILED_TO_CHANGE_MENU_ITEM_CATEGORIES_ORDER';
